# http://www.appveyor.com/docs/appveyor-yml

# Use 'unstable' build worker image as it contains Cygwin
os: Unstable

branches:
  only:
    - master

environment:
  global:
    CYG_ROOT: C:/cygwin
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    CYG_CACHE: C:/cygwin/var/cache/setup
    OPAM_DIR: C:/opam
#    OPAMDEBUG: true

cache:
  - C:\opam
  - C:\cygwin\var\cache\setup

# Do a shallow clone of the repo to speed up the build
clone_depth: 1

install:
  - set PATH=%OPAM_DIR%\bin;%PATH%
#  - appveyor DownloadFile "http://cygwin.com/setup-%CYG_ARCH%.exe" -FileName "%CYG_ROOT%\setup-x86.exe"
  - '"%CYG_ROOT%\setup-x86.exe" -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P make -P gcc-core -P ocaml -P ocaml-compiler-libs -P m4 -P tar -P patch -P flexdll >NUL'
  - '%CYG_ROOT%\bin\bash -lc "cygcheck -dc cygwin"'
  - '%CYG_ROOT%\bin\bash -lc "echo \"OCaml version `ocamlc -version`\""'
  - appveyor_install.cmd

build_script:
  - '%CYG_ROOT%\bin\bash -lc "git clone --quiet https://github.com/Chris00/opam-repository.git"'
  - '%CYG_ROOT%\bin\bash -lc "opam init -y -a opam-repository"'
  - '%CYG_ROOT%/bin/bash -lc "eval $(opam config env) && opam install -y oasis && opam remove -y oasis"'
#  - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ocaml test.ml"'

# test_script:
#   - '%CYG_ROOT%/bin/bash -lc "oasis --help"'
