# http://www.appveyor.com/docs/appveyor-yml

# Use 'unstable' build worker image as it contains Cygwin
os: Unstable

branches:
  only:
    - master

environment:
  global:
    CYG_ROOT: C:/cygwin
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    CYG_CACHE: C:/cygwin/var/cache/setup
    OPAM_DIR: C:/opam
#    OPAMDEBUG: true

cache:
  - C:\opam

init:
  - echo System architecture %PLATFORM%

install:
  - set PATH=%OPAM_DIR%\bin;%PATH%
  - appveyor_install.cmd

build_script:
  - '%CYG_ROOT%\bin\bash -lc "git clone --quiet https://github.com/Chris00/opam-repository.git"'
  - '%CYG_ROOT%\bin\bash -lc "opam init -y -a opam-repository"'
  - '%CYG_ROOT%/bin/bash -lc "eval $(opam config env) && opam install -y mindstorm"'

# test_script:
#   - '%CYG_ROOT%/bin/bash -lc "oasis --help"'
